### ISSUE TITLE
Assets fail to load if directory path is wrong

### ISSUE THREAD

**Issue by paaljoachim** [danieltj27/Toolbar#10]
I downloaded and activated the 2.0 version on a simple local test site running Desktop Server version 3.8.4.

![screen shot 2018-04-25 at 14 31 41](https://user-images.githubusercontent.com/5323259/39246488-0bc4b132-4897-11e8-95aa-fca2a932cb29.png)

I check the frontend.

![screen shot 2018-04-25 at 14 44 02](https://user-images.githubusercontent.com/5323259/39246527-208d5b28-4897-11e8-8fac-3155839b1cbb.png)

Console errors that showed up are:
![screen shot 2018-04-25 at 14 45 19](https://user-images.githubusercontent.com/5323259/39246596-51181f76-4897-11e8-899f-de1869839fd1.png)

I did a hard refresh in Chrome and I also installed Autoptimize to also clear the cache.
The error remained the same.

**Comment by danieltj27** [comment]
Can you check inside the plugin folder and see if those resources are present?

Additionally, where is the browser actually looking to load those files from?

**Comment by paaljoachim** [comment]
I see that the files are present.
I also tested Firefox. 

I also installed it on an older client site that I have online:
http://fragmentsofawalk.com/sjelefode
http://fragmentsofawalk.com/sjelefode/wp-admin
NEW TEST USER
Username: test
Password: I will just paste it into the direct message to you through slack.

**Comment by danieltj27** [comment]
You don't need to create a test account. I'll test on my local development site. I'd advise against installing this on a client site in the plugins current state anyway as it's still a working progress.

I'd suggest deactivating all other plugins and trying again to see if that works.

**Comment by paaljoachim** [comment]
I have earlier cloned the client site to its real domain. What is left is a client dev site I need to delete. I deactivated all other plugins and switched to Twenty Sixteen theme. There is no change.

**Comment by danieltj27** [comment]
What’s the path to the plugins folder where the plugin files are being kept? The plugin files need to be inside a folder called `toolbar` and lowercase. So it’s like:

```
wp-content/plugins/toolbar/
```

Is it like that or is it names differently? I suspect it has a different folder name as it’s downloaded directly from GitHub.

**Comment by paaljoachim** [comment]
The path is: wp-content/plugins/Toolbar-master (default path from the plugin downloaded from here. So yeah your right.)
I changed it to toolbar and now it works.

Btw Hovering the links on the frontend does not make the words blue. The icons and text is all in white.

**Comment by danieltj27** [comment]
Ah great, I thought that might be the case. I’ll leave this open though as it’s worth changing the directory so it does fail like this. 

Could you open a new issue about the link colour if you have time?

**Comment by danieltj27** [comment]
There doesn't seem to be an easy way to work out the current directory name reliably to fetch the assets here so I'm closing this as a 'won't fix'.

I may come back to this in the future if a decent method surfaces, but for now ensuring the plugin folder is called `/toolbar/` is the easiest way forward.

Thanks for letting me know about this though. I've tweaked the `plugin_url` function slightly in commit f4614bc but of course this is still a thing.
