### ISSUE TITLE
Clicking site title while in backend to enter frontend

### ISSUE THREAD

**Issue by paaljoachim** [danieltj27/Toolbar#9]
Hei Daniel

The existing top admin toolbar to enter the frontend/visit site.
![screen shot 2018-04-25 at 14 17 05](https://user-images.githubusercontent.com/5323259/39245215-5c7a428a-4893-11e8-90dc-57f576cd1652.png)

The user can select to click the site title or the words Visit Site to enter the frontend.

The toolbar plugin adjust this so one only can click the site title to enter the frontend.
A few thoughts come up.
1. Should there be visible clarity to better show that clicking the site title enters the frontend?
2. Should the site title be moved to the middle of the toolbar? So that one can instead use the words Visit Site.

![top-admin-toolbar](https://user-images.githubusercontent.com/5323259/39245390-ecf30cca-4893-11e8-90c2-b5a6203331bb.jpg)

Other solutions?

**Comment by danieltj27** [comment]
Hi, thanks for raising this issue. The plugin in this repo is version 2.0 (not finished and not released on WordPress.org just yet). However, the view site option [has been added back in](https://github.com/danieltj27/Toolbar/blob/master/toolbar.php#L592) so this can be considered fixed now. 👍
